version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:18
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            npm ci --legacy-peer-deps
            npm run electron:build
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
